export {
  QuizDomainError,
  QuizOperationFailedError,
  QuizNotFoundError,
  QuizForbiddenError,
  QuizSlugConflictError,
  QuizConflictError,
  QuizValidationError,
  QuizVersionImmutableError,
  QuizVersionNotFoundError,
  QuizInsufficientQuestionsError,
  QuizQuestionPositionConflictError,
  QuizAnswerOptionPositionConflictError,
  QuizMultipleCorrectOptionsError,
} from './quiz-domain.errors';
