import { BadRequestException } from '@nestjs/common';
import { decodeBase64JsonCursor, encodeBase64JsonCursor } from '@/common/utils/cursor.util';
import type { ReviewCursor, ReviewHelpfulCursor, ReportCursor } from '../domain/ports';

// RFC 9562 UUIDv7: third group's first hex digit is `7`
// (version), fourth group's first hex digit is `8`, `9`, `a`, or
// `b` (variant). The previous pattern enforced `[1-5]` for the
// version digit which rejected every v7 UUID — including all
// primary keys generated by the app and by Postgres' `uuidv7()`
// extension — and forced every cursor decode to throw a 400.
// Tier 2 cursors use the same lower-cased hyphenated form as
// `generateUuidV7()` and `pg_uuidv7`, so the regex mirrors that.
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

// Phase 5 / Issue #10 — the previous regex `^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}`
// accepted a *prefix* of an ISO timestamp with no timezone or trailing
// characters. A cursor like `2026-01-01T99:99:99` validated and then
// crashed the SQL `WHERE` clause with a Postgres error and surfaced
// as a 500. Tighten the pattern to require either `Z` or a numeric
// UTC offset. Milliseconds are optional but, when present, must be
// well-formed (one to nine digits, see [ISO 8601 §4.2.2.2]).
const ISO_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$/;

function isUuid(value: unknown): boolean {
  return typeof value === 'string' && UUID_PATTERN.test(value);
}

function isIsoDateString(value: unknown): value is string {
  return typeof value === 'string' && ISO_DATE_PATTERN.test(value);
}

export class CursorMapper {
  static parseReview(cursor: string): ReviewCursor {
    const parsed = decodeBase64JsonCursor<{ createdAt?: string; reviewId?: string }>(cursor);

    if (!isIsoDateString(parsed.createdAt) || !isUuid(parsed.reviewId)) {
      // Phase 5 / Issue #10 — surface malformed cursors as a 400
      // instead of letting the generic `Error` fall through to the
      // 500 path. A typo'd cursor must not crash the request.
      throw new BadRequestException('Invalid cursor');
    }

    return {
      createdAt: parsed.createdAt,
      reviewId: parsed.reviewId!,
    };
  }

  static serializeReview(payload: ReviewCursor): string {
    return encodeBase64JsonCursor({
      createdAt: payload.createdAt,
      reviewId: payload.reviewId,
    });
  }

  // Phase 5 / Issue #11 — separate cursor shape for the
  // `helpful` sort. The cursor carries the same columns as the
  // ORDER BY (`helpful_count DESC, review_id DESC`) so the
  // repository's predicate matches the sort key and pagination
  // is stable across pages.
  static parseHelpful(cursor: string): ReviewHelpfulCursor {
    const parsed = decodeBase64JsonCursor<{
      helpfulCount?: number;
      reviewId?: string;
    }>(cursor);

    if (
      typeof parsed.helpfulCount !== 'number' ||
      !Number.isInteger(parsed.helpfulCount) ||
      parsed.helpfulCount < 0 ||
      !isUuid(parsed.reviewId)
    ) {
      throw new BadRequestException('Invalid cursor');
    }

    return {
      helpfulCount: parsed.helpfulCount,
      reviewId: parsed.reviewId!,
    };
  }

  static serializeHelpful(payload: ReviewHelpfulCursor): string {
    return encodeBase64JsonCursor({
      helpfulCount: payload.helpfulCount,
      reviewId: payload.reviewId,
    });
  }

  static parseReport(cursor: string): ReportCursor {
    const parsed = decodeBase64JsonCursor<{ createdAt?: string; reportId?: string }>(cursor);

    if (!isIsoDateString(parsed.createdAt) || !isUuid(parsed.reportId)) {
      throw new BadRequestException('Invalid cursor');
    }

    return {
      createdAt: parsed.createdAt,
      reportId: parsed.reportId!,
    };
  }

  static serializeReport(payload: ReportCursor): string {
    return encodeBase64JsonCursor({
      createdAt: payload.createdAt,
      reportId: payload.reportId,
    });
  }
}
