import { ApiExtraModels, ApiProperty, ApiPropertyOptional, getSchemaPath } from '@nestjs/swagger';
import { RFC7807_TYPE_URIS } from '@/common/types/problem-detail.type';

/**
 * RFC 7807 Problem Details for HTTP APIs.
 *
 * @see https://tools.ietf.org/html/rfc7807
 */
export class ProblemDetailDto {
  @ApiProperty({
    description: 'URI reference that identifies the problem type',
    example: RFC7807_TYPE_URIS[404],
  })
  type!: string;

  @ApiProperty({
    description: 'Short, human-readable summary of the problem type',
    example: 'NotFound',
  })
  title!: string;

  @ApiProperty({
    description: 'HTTP status code generated by the origin server',
    example: 404,
  })
  status!: number;

  @ApiPropertyOptional({
    description: 'Human-readable explanation specific to this occurrence of the problem',
    example: 'The requested resource was not found',
  })
  detail?: string;

  @ApiPropertyOptional({
    description: 'URI reference that identifies the specific occurrence of the problem',
    example: '/quizzes/660e8400-e29b-41d4-a716-446655440000',
  })
  instance?: string;

  @ApiPropertyOptional({
    description: 'Additional problem-specific fields (e.g., requestId, validation errors)',
    example: { requestId: 'req_abc123' },
  })
  extensions?: Record<string, unknown>;
}

/**
 * Response schemas for common RFC 7807 error types with realistic examples.
 * These are used with @ApiBadRequestResponse, @ApiUnauthorizedResponse, etc.
 */
export const ErrorResponseExamples = {
  badRequest: {
    type: RFC7807_TYPE_URIS[400],
    title: 'BadRequest',
    status: 400,
    detail: 'Request validation failed',
    instance: '/api/v1/endpoint',
    extensions: {
      errors: ['email must be an email', 'password must be longer than 5 characters'],
      requestId: 'req_abc123',
    },
  },
  unauthorized: {
    type: RFC7807_TYPE_URIS[401],
    title: 'Unauthorized',
    status: 401,
    detail: 'Invalid or expired access token',
    instance: '/api/v1/endpoint',
    extensions: { requestId: 'req_abc123' },
  },
  forbidden: {
    type: RFC7807_TYPE_URIS[403],
    title: 'Forbidden',
    status: 403,
    detail: 'You do not have permission to perform this action',
    instance: '/api/v1/endpoint',
    extensions: { requestId: 'req_abc123' },
  },
  notFound: {
    type: RFC7807_TYPE_URIS[404],
    title: 'NotFound',
    status: 404,
    detail: 'The requested resource was not found',
    instance: '/api/v1/endpoint',
    extensions: { requestId: 'req_abc123' },
  },
  conflict: {
    type: RFC7807_TYPE_URIS[409],
    title: 'Conflict',
    status: 409,
    detail: 'The request conflicts with the current state of the resource',
    instance: '/api/v1/endpoint',
    extensions: { requestId: 'req_abc123' },
  },
  tooManyRequests: {
    type: RFC7807_TYPE_URIS[429],
    title: 'TooManyRequests',
    status: 429,
    detail: 'Rate limit exceeded. Please try again later',
    instance: '/api/v1/endpoint',
    extensions: { requestId: 'req_abc123', retryAfter: 60 },
  },
  internalServerError: {
    type: RFC7807_TYPE_URIS[500],
    title: 'InternalServerError',
    status: 500,
    detail: 'An unexpected error occurred',
    instance: '/api/v1/endpoint',
    extensions: { requestId: 'req_abc123' },
  },
} as const;

/**
 * Pagination metadata for cursor-based pagination.
 *
 * The `kind: 'cursor'` discriminator is required starting with the response
 * envelope migration (see docs/migrations/RESPONSE_ENVELOPE_MIGRATION.md).
 * Existing consumers continue to receive `limit`, `nextCursor`, `hasNextPage`
 * as before — the new field is additive on the wire only after Phase 4 ships.
 */
export class PaginationMetaDto {
  @ApiProperty({
    description: 'Discriminator field. Always "cursor" for cursor pagination.',
    example: 'cursor',
  })
  kind!: 'cursor';

  @ApiProperty({ description: 'Number of items returned in this page', example: 20 })
  limit!: number;

  @ApiProperty({
    description:
      'Opaque cursor string for fetching the next page. `null` when there is no next page.',
    // Phase 4 (audit issue 3.3): explicit `type: 'string'` was missing
    // — when `@ApiPropertyOptional({ nullable: true })` is paired with
    // `string | null`, the swagger plugin emits `{ type: 'object' }`
    // (or worse, `{ type: 'object', nullable: true }`) in the
    // generated `openapi.json`, which breaks generated SDKs that try
    // to type the cursor as a JS string. Forcing `type: 'string'`
    // here aligns the OpenAPI artifact with the runtime wire shape.
    type: 'string',
    example: 'eyJjcmVhdGVkQXQiOiIyMDI1LTAxLTAxVDAwOjAwOjAwKzAwOjAwIn0',
    nullable: true,
  })
  nextCursor!: string | null;

  @ApiProperty({ description: 'Whether more items exist after this page', example: true })
  hasNextPage!: boolean;
}

/**
 * Pagination metadata for offset-based pagination. Used by leaderboards,
 * tournaments, ranking tables, and any endpoint that requires random-access
 * page jumps (`?page=5`) or total counts.
 *
 * Counterpart of {@link PaginationMetaDto}; disambiguated at runtime via `kind`.
 */
export class OffsetPaginationMetaDto {
  @ApiProperty({
    description: 'Discriminator field. Always "offset" for offset pagination.',
    example: 'offset',
  })
  kind!: 'offset';

  @ApiProperty({ description: '1-indexed page number that was just returned', example: 1 })
  page!: number;

  @ApiProperty({ description: 'Maximum number of items per page', example: 20 })
  limit!: number;

  @ApiProperty({ description: 'Total number of items matching the query', example: 1342 })
  total!: number;

  @ApiProperty({ description: 'Whether more pages exist after the current one', example: true })
  hasMore!: boolean;
}

/**
 * Concrete paginated response wrapper for cursor-based pagination.
 * Use this when the item type is known at compile time.
 *
 * @example
 * // For QuizListResponseDto:
 * class QuizListResponseDto {
 *   @ApiProperty({ type: () => [QuizResponseDto] })
 *   items!: QuizResponseDto[];
 *
 *   @ApiProperty({ type: () => PaginationMetaDto })
 *   pagination!: PaginationMetaDto;
 * }
 */
export class PaginatedResponseDto {
  @ApiProperty({ description: 'Items for the current page', type: () => [Object] })
  items!: object[];

  @ApiProperty({ description: 'Pagination metadata', type: () => PaginationMetaDto })
  pagination!: PaginationMetaDto;
}

/**
 * Query parameters for cursor-based pagination.
 */
export class CursorQueryDto {
  @ApiPropertyOptional({
    description: 'Opaque cursor string from a previous response for cursor-based pagination',
    example:
      'eyJjcmVhdGVkQXQiOiIyMDI1LTAxLTAxVDAwOjAwOjAwKzAwOjAwIiwiY3JlYXRpbmdVc2VySWQiOiI4MTIzMTIzLTEyMzQtMTIzNC0xMjM0LTEyMzQxMjM0MTIzNDQifQ',
    nullable: true,
  })
  cursor?: string | null;
}

/**
 * Query parameters for page size limit.
 */
export class LimitQueryDto {
  @ApiPropertyOptional({
    description: 'Maximum number of items to return per page',
    minimum: 1,
    maximum: 100,
    default: 20,
    example: 20,
  })
  limit?: number | null;
}

/**
 * Simple success response with a message.
 *
 * Use this DTO for simple action confirmation responses (e.g., "Category followed successfully").
 * This is the canonical shared MessageResponseDto — do not create module-specific duplicates.
 */
export class MessageResponseDto {
  @ApiProperty({
    description: 'Human-readable confirmation message',
    example: 'Operation completed successfully',
  })
  message!: string;
}

/**
 * @deprecated Use {@link MessageResponseDto} instead. Kept for backward compatibility.
 */
export class SuccessResponseDto {
  @ApiProperty({ description: 'Confirmation message', example: 'Operation completed successfully' })
  message!: string;
}

// ─── Response envelope wrappers ─────────────────────────────────────────────────
//
// All HTTP responses are wrapped by ResponseFormatInterceptor as:
//   { data: <actual_response>, meta: { timestamp, ...pagination } }
//
// These DTOs document the envelope so that every @ApiOkResponse / @ApiCreatedResponse
// reference can use the `type: () => WrappedDto<T>()` pattern.
//
// Usage in controllers:
//   @ApiOkResponse({ type: () => WrappedSuccessDto() })
//   @ApiCreatedResponse({ type: () => WrappedLoginDto() })
//
// Non-paginated plain-object responses use WrappedDto<T>.
// Paginated responses (items + pagination at root) use WrappedPaginatedDto<T>.

/**
 * Meta field added by ResponseFormatInterceptor to every non-paginated response.
 */
export class ResponseMetaDto {
  @ApiProperty({
    description: 'ISO 8601 timestamp of when the response was generated',
    format: 'date-time',
    example: '2026-06-25T10:30:00.000Z',
  })
  timestamp!: string;
}

/**
 * Paginated response meta — includes timestamp plus pagination fields.
 *
 * Phase 4 (audit issue 3.3): the `pagination` field previously had
 * `type: 'object'` and no schema reference, which caused SDK generators
 * to emit a generic `Record<string, unknown>`. It is now typed as a
 * oneOf of the two canonical pagination metas (`PaginationMetaDto` for
 * cursor, `OffsetPaginationMetaDto` for offset) so generated clients
 * can switch on the `kind` discriminator.
 */
export class PaginatedResponseMetaDto extends ResponseMetaDto {
  @ApiExtraModels(PaginationMetaDto, OffsetPaginationMetaDto)
  @ApiPropertyOptional({
    description: 'Pagination metadata — discriminated by the `kind` field',
    oneOf: [
      { $ref: getSchemaPath(PaginationMetaDto) },
      { $ref: getSchemaPath(OffsetPaginationMetaDto) },
    ],
  })
  pagination?: PaginationMetaDto | OffsetPaginationMetaDto;
}

/**
 * Generic non-paginated response envelope.
 *
 * @example
 * // For a simple message response:
 * WrappedDto<{ message: string }>
 * // Runtime shape: { data: { message: string }, meta: { timestamp: string } }
 */
export class WrappedDto<T extends object> {
  @ApiProperty({ description: 'The actual response payload for this endpoint' })
  data!: T;

  @ApiProperty({ type: () => ResponseMetaDto, description: 'Response metadata' })
  meta!: ResponseMetaDto;
}

/**
 * Generic paginated response envelope.
 *
 * @example
 * WrappedPaginatedDto<QuizResponseDto>
 * // Runtime shape: { data: QuizResponseDto[], meta: { timestamp: string, pagination: {...} } }
 */
export class WrappedPaginatedDto<T extends object> {
  @ApiProperty({
    description: 'Items for the current page',
    isArray: true,
    type: () => Object,
  })
  data!: T[];

  @ApiProperty({ type: () => PaginatedResponseMetaDto })
  meta!: PaginatedResponseMetaDto;
}

/**
 * Convenience wrapper for simple `{ message: string }` responses.
 */
export class WrappedSuccessDto extends WrappedDto<{ message: string }> {}

/**
 * Convenience wrapper for `{ available: boolean }` responses.
 */
export class WrappedBooleanDto extends WrappedDto<{ available: boolean }> {}

/**
 * Convenience wrapper for `{ valid: boolean }` responses.
 */
export class WrappedValidDto extends WrappedDto<{ valid: boolean }> {}

/**
 * Convenience wrapper for `{ accessToken: string }` responses.
 */
export class WrappedAccessTokenDto extends WrappedDto<{ accessToken: string }> {}
