import { ApiExtraModels, ApiProperty, ApiPropertyOptional, getSchemaPath } from '@nestjs/swagger';
import { RFC7807_TYPE_URIS } from '@/common/types/problem-detail.type';

export class ProblemDetailDto {
  @ApiProperty({
    description: 'URI reference that identifies the problem type',
    example: RFC7807_TYPE_URIS[404],
  })
  type!: string;

  @ApiProperty({
    description: 'Short, human-readable summary of the problem type',
    example: 'NotFound',
  })
  title!: string;

  @ApiProperty({
    description: 'HTTP status code generated by the origin server',
    example: 404,
  })
  status!: number;

  @ApiPropertyOptional({
    description: 'Human-readable explanation specific to this occurrence of the problem',
    example: 'The requested resource was not found',
  })
  detail?: string;

  @ApiPropertyOptional({
    description: 'URI reference that identifies the specific occurrence of the problem',
    example: '/quizzes/660e8400-e29b-71d4-a716-446655440000',
  })
  instance?: string;

  @ApiPropertyOptional({
    description: 'Additional problem-specific fields (e.g., requestId, validation errors)',
    example: { requestId: 'req_abc123' },
  })
  extensions?: Record<string, unknown>;
}

export const ErrorResponseExamples = {
  badRequest: {
    type: RFC7807_TYPE_URIS[400],
    title: 'BadRequest',
    status: 400,
    detail: 'Request validation failed',
    instance: '/api/v1/endpoint',
    extensions: {
      errors: ['email must be an email', 'password must be longer than 5 characters'],
      requestId: 'req_abc123',
    },
  },
  unauthorized: {
    type: RFC7807_TYPE_URIS[401],
    title: 'Unauthorized',
    status: 401,
    detail: 'Invalid or expired access token',
    instance: '/api/v1/endpoint',
    extensions: { requestId: 'req_abc123' },
  },
  forbidden: {
    type: RFC7807_TYPE_URIS[403],
    title: 'Forbidden',
    status: 403,
    detail: 'You do not have permission to perform this action',
    instance: '/api/v1/endpoint',
    extensions: { requestId: 'req_abc123' },
  },
  notFound: {
    type: RFC7807_TYPE_URIS[404],
    title: 'NotFound',
    status: 404,
    detail: 'The requested resource was not found',
    instance: '/api/v1/endpoint',
    extensions: { requestId: 'req_abc123' },
  },
  conflict: {
    type: RFC7807_TYPE_URIS[409],
    title: 'Conflict',
    status: 409,
    detail: 'The request conflicts with the current state of the resource',
    instance: '/api/v1/endpoint',
    extensions: { requestId: 'req_abc123' },
  },
  tooManyRequests: {
    type: RFC7807_TYPE_URIS[429],
    title: 'TooManyRequests',
    status: 429,
    detail: 'Rate limit exceeded. Please try again later',
    instance: '/api/v1/endpoint',
    extensions: { requestId: 'req_abc123', retryAfter: 60 },
  },
  internalServerError: {
    type: RFC7807_TYPE_URIS[500],
    title: 'InternalServerError',
    status: 500,
    detail: 'An unexpected error occurred',
    instance: '/api/v1/endpoint',
    extensions: { requestId: 'req_abc123' },
  },
} as const;

export class PaginationMetaDto {
  @ApiProperty({
    description: 'Discriminator field. Always "cursor" for cursor pagination.',
    example: 'cursor',
  })
  kind!: 'cursor';

  @ApiProperty({ description: 'Number of items returned in this page', example: 20 })
  limit!: number;

  @ApiProperty({
    description:
      'Opaque cursor string for fetching the next page. `null` when there is no next page.',
    type: 'string',
    example: 'eyJjcmVhdGVkQXQiOiIyMDI1LTAxLTAxVDAwOjAwOjAwKzAwOjAwIn0',
    nullable: true,
  })
  nextCursor!: string | null;

  @ApiProperty({ description: 'Whether more items exist after this page', example: true })
  hasNextPage!: boolean;
}

export class OffsetPaginationMetaDto {
  @ApiProperty({
    description: 'Discriminator field. Always "offset" for offset pagination.',
    example: 'offset',
  })
  kind!: 'offset';

  @ApiProperty({ description: '1-indexed page number that was just returned', example: 1 })
  page!: number;

  @ApiProperty({ description: 'Maximum number of items per page', example: 20 })
  limit!: number;

  @ApiProperty({ description: 'Total number of items matching the query', example: 1342 })
  total!: number;

  @ApiProperty({ description: 'Whether more pages exist after the current one', example: true })
  hasMore!: boolean;
}

export class PaginatedResponseDto {
  @ApiProperty({ description: 'Items for the current page', type: () => [Object] })
  items!: object[];

  @ApiProperty({ description: 'Pagination metadata', type: () => PaginationMetaDto })
  pagination!: PaginationMetaDto;
}

export class CursorQueryDto {
  @ApiPropertyOptional({
    description: 'Opaque cursor string from a previous response for cursor-based pagination',
    example:
      'eyJjcmVhdGVkQXQiOiIyMDI1LTAxLTAxVDAwOjAwOjAwKzAwOjAwIiwiY3JlYXRpbmdVc2VySWQiOiI4MTIzMTIzLTEyMzQtMTIzNC0xMjM0LTEyMzQxMjM0MTIzNDQifQ',
    nullable: true,
  })
  cursor?: string | null;
}

export class LimitQueryDto {
  @ApiPropertyOptional({
    description: 'Maximum number of items to return per page',
    minimum: 1,
    maximum: 100,
    default: 20,
    example: 20,
  })
  limit?: number | null;
}

export class MessageResponseDto {
  @ApiProperty({
    description: 'Human-readable confirmation message',
    example: 'Operation completed successfully',
  })
  message!: string;
}

export class SuccessResponseDto {
  @ApiProperty({ description: 'Confirmation message', example: 'Operation completed successfully' })
  message!: string;
}
export class ResponseMetaDto {
  @ApiProperty({
    description: 'ISO 8601 timestamp of when the response was generated',
    format: 'date-time',
    example: '2026-06-25T10:30:00.000Z',
  })
  timestamp!: string;
}

export class PaginatedResponseMetaDto extends ResponseMetaDto {
  @ApiExtraModels(PaginationMetaDto, OffsetPaginationMetaDto)
  @ApiPropertyOptional({
    description: 'Pagination metadata — discriminated by the `kind` field',
    oneOf: [
      { $ref: getSchemaPath(PaginationMetaDto) },
      { $ref: getSchemaPath(OffsetPaginationMetaDto) },
    ],
  })
  pagination?: PaginationMetaDto | OffsetPaginationMetaDto;
}

export class WrappedDto<T extends object> {
  @ApiProperty({ description: 'The actual response payload for this endpoint' })
  data!: T;

  @ApiProperty({ type: () => ResponseMetaDto, description: 'Response metadata' })
  meta!: ResponseMetaDto;
}

export class WrappedPaginatedDto<T extends object> {
  @ApiProperty({
    description: 'Items for the current page',
    isArray: true,
    type: () => Object,
  })
  data!: T[];

  @ApiProperty({ type: () => PaginatedResponseMetaDto })
  meta!: PaginatedResponseMetaDto;
}

export class WrappedSuccessDto extends WrappedDto<{ message: string }> {}

export class WrappedBooleanDto extends WrappedDto<{ available: boolean }> {}

export class WrappedValidDto extends WrappedDto<{ valid: boolean }> {}

export class WrappedAccessTokenDto extends WrappedDto<{ accessToken: string }> {}
