import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { RFC7807_TYPE_URIS } from '@/common/types/problem-detail.type';

/**
 * RFC 7807 Problem Details for HTTP APIs.
 *
 * @see https://tools.ietf.org/html/rfc7807
 */
export class ProblemDetailDto {
  @ApiProperty({
    description: 'URI reference that identifies the problem type',
    example: RFC7807_TYPE_URIS[404],
  })
  type!: string;

  @ApiProperty({
    description: 'Short, human-readable summary of the problem type',
    example: 'NotFound',
  })
  title!: string;

  @ApiProperty({
    description: 'HTTP status code generated by the origin server',
    example: 404,
  })
  status!: number;

  @ApiPropertyOptional({
    description: 'Human-readable explanation specific to this occurrence of the problem',
    example: 'The requested resource was not found',
  })
  detail?: string;

  @ApiPropertyOptional({
    description: 'URI reference that identifies the specific occurrence of the problem',
    example: '/quizzes/660e8400-e29b-41d4-a716-446655440000',
  })
  instance?: string;

  @ApiPropertyOptional({
    description: 'Additional problem-specific fields (e.g., requestId, validation errors)',
    example: { requestId: 'req_abc123' },
  })
  extensions?: Record<string, unknown>;
}

/**
 * Response schemas for common RFC 7807 error types with realistic examples.
 * These are used with @ApiBadRequestResponse, @ApiUnauthorizedResponse, etc.
 */
export const ErrorResponseExamples = {
  badRequest: {
    type: RFC7807_TYPE_URIS[400],
    title: 'BadRequest',
    status: 400,
    detail: 'Request validation failed',
    instance: '/quizzes',
    extensions: {
      errors: ['email must be an email', 'password must be longer than 5 characters'],
      requestId: 'req_abc123',
    },
  },
  unauthorized: {
    type: RFC7807_TYPE_URIS[401],
    title: 'Unauthorized',
    status: 401,
    detail: 'Invalid or expired access token',
    instance: '/auth/login',
    extensions: { requestId: 'req_abc123' },
  },
  forbidden: {
    type: RFC7807_TYPE_URIS[403],
    title: 'Forbidden',
    status: 403,
    detail: 'You do not have permission to perform this action',
    instance: '/quizzes/660e8400-e29b-41d4-a716-446655440000',
    extensions: { requestId: 'req_abc123' },
  },
  notFound: {
    type: RFC7807_TYPE_URIS[404],
    title: 'NotFound',
    status: 404,
    detail: 'The requested resource was not found',
    instance: '/quizzes/660e8400-e29b-41d4-a716-446655440000',
    extensions: { requestId: 'req_abc123' },
  },
  conflict: {
    type: RFC7807_TYPE_URIS[409],
    title: 'Conflict',
    status: 409,
    detail: 'The request conflicts with the current state of the resource',
    instance: '/quizzes/660e8400-e29b-41d4-a716-446655440000',
    extensions: { requestId: 'req_abc123' },
  },
  tooManyRequests: {
    type: RFC7807_TYPE_URIS[429],
    title: 'TooManyRequests',
    status: 429,
    detail: 'Rate limit exceeded. Please try again later',
    instance: '/auth/login',
    extensions: { requestId: 'req_abc123', retryAfter: 60 },
  },
  internalServerError: {
    type: RFC7807_TYPE_URIS[500],
    title: 'InternalServerError',
    status: 500,
    detail: 'An unexpected error occurred',
    instance: '/quizzes',
    extensions: { requestId: 'req_abc123' },
  },
} as const;

/**
 * Pagination metadata for cursor-based pagination.
 */
export class PaginationMetaDto {
  @ApiProperty({ description: 'Number of items returned in this page', example: 20 })
  limit!: number;

  @ApiPropertyOptional({
    description:
      'Opaque cursor string for fetching the next page. `null` when there is no next page.',
    example:
      'eyJjcmVhdGVkQXQiOiIyMDI1LTAxLTAxVDAwOjAwOjAwKzAwOjAwIiwiY3JlYXRpbmdVc2VySWQiOiI4MTIzMTIzLTEyMzQtMTIzNC0xMjM0LTEyMzQxMjM0MTIzNDQifQ',
    nullable: true,
  })
  nextCursor!: string | null;

  @ApiProperty({ description: 'Whether more items exist after this page', example: true })
  hasNextPage!: boolean;
}

/**
 * Concrete paginated response wrapper for cursor-based pagination.
 * Use this when the item type is known at compile time.
 *
 * @example
 * // For QuizListResponseDto:
 * class QuizListResponseDto {
 *   @ApiProperty({ type: () => [QuizResponseDto] })
 *   items!: QuizResponseDto[];
 *
 *   @ApiProperty({ type: () => PaginationMetaDto })
 *   pagination!: PaginationMetaDto;
 * }
 */
export class PaginatedResponseDto {
  @ApiProperty({ description: 'Items for the current page', type: () => [Object] })
  items!: object[];

  @ApiProperty({ description: 'Pagination metadata', type: () => PaginationMetaDto })
  pagination!: PaginationMetaDto;
}

/**
 * Query parameters for cursor-based pagination.
 */
export class CursorQueryDto {
  @ApiPropertyOptional({
    description: 'Opaque cursor string from a previous response for cursor-based pagination',
    example:
      'eyJjcmVhdGVkQXQiOiIyMDI1LTAxLTAxVDAwOjAwOjAwKzAwOjAwIiwiY3JlYXRpbmdVc2VySWQiOiI4MTIzMTIzLTEyMzQtMTIzNC0xMjM0LTEyMzQxMjM0MTIzNDQifQ',
    nullable: true,
  })
  cursor?: string | null;
}

/**
 * Query parameters for page size limit.
 */
export class LimitQueryDto {
  @ApiPropertyOptional({
    description: 'Maximum number of items to return per page',
    minimum: 1,
    maximum: 100,
    default: 20,
    example: 20,
  })
  limit?: number | null;
}

/**
 * Simple success response with a message.
 */
export class SuccessResponseDto {
  @ApiProperty({ description: 'Confirmation message', example: 'Operation completed successfully' })
  message!: string;
}
