ALTER TABLE "auth_audit_logs" ALTER COLUMN "audit_log_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "badge_rules" ALTER COLUMN "rule_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "badges" ALTER COLUMN "badge_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "blocked_users" ALTER COLUMN "block_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "bookmark_collections" ALTER COLUMN "collection_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "bookmarked_quizzes" ALTER COLUMN "bookmark_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "categories" ALTER COLUMN "category_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "category_follows" ALTER COLUMN "follow_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "discussion_comments" ALTER COLUMN "comment_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "discussion_reports" ALTER COLUMN "report_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "discussion_threads" ALTER COLUMN "thread_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "discussion_votes" ALTER COLUMN "vote_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "friendships" ALTER COLUMN "friendship_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "notification_preferences" ALTER COLUMN "preferences_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "notifications" ALTER COLUMN "notification_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "oauth_accounts" ALTER COLUMN "oauth_account_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "outbox_events" ALTER COLUMN "event_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "password_history" ALTER COLUMN "history_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "password_reset_tokens" ALTER COLUMN "password_reset_token_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "quiz_answer_options" ALTER COLUMN "option_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "quiz_attempt_answers" ALTER COLUMN "attempt_answer_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "quiz_attempts" ALTER COLUMN "attempt_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "quiz_categories" ALTER COLUMN "quiz_category_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "quiz_instance_players" ALTER COLUMN "instance_player_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "quiz_instances" ALTER COLUMN "instance_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "quiz_questions" ALTER COLUMN "question_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "quiz_reviews" ALTER COLUMN "review_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "quiz_tags" ALTER COLUMN "quiz_tag_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "quiz_versions" ALTER COLUMN "quiz_version_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "quizzes" ALTER COLUMN "quiz_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "rank_history" ALTER COLUMN "history_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "rank_recalculation_work_items" ALTER COLUMN "work_item_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "ranking_milestones" ALTER COLUMN "id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "review_helpful_votes" ALTER COLUMN "vote_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "review_reports" ALTER COLUMN "report_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "sent_verification_tokens" ALTER COLUMN "sent_token_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "social_feed_activities" ALTER COLUMN "activity_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "tag_follows" ALTER COLUMN "follow_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "tags" ALTER COLUMN "tag_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "tournament_participants" ALTER COLUMN "participant_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "tournament_round_participants" ALTER COLUMN "round_participant_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "tournament_rounds" ALTER COLUMN "round_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "tournaments" ALTER COLUMN "tournament_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "user_activity_events" ALTER COLUMN "event_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "user_badges" ALTER COLUMN "user_badge_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "user_follows" ALTER COLUMN "follow_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "user_profile_settings" ALTER COLUMN "settings_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "user_profiles" ALTER COLUMN "profile_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "user_sessions" ALTER COLUMN "session_id" SET DEFAULT uuidv7();--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "user_id" SET DEFAULT uuidv7();