-- Migration: Remove title/description from user_activity_events
-- Store only facts in metadata; presentation is generated by application layer

-- Step 1: Add check constraint for non-empty metadata (will apply to new rows)
ALTER TABLE "user_activity_events" ADD CONSTRAINT "user_activity_events_metadata_not_empty" CHECK (metadata <> '{}'::jsonb);

-- Step 2: Remove the title column (and its check constraint)
ALTER TABLE "user_activity_events" DROP CONSTRAINT "user_activity_events_title_nonblank" CASCADE;
ALTER TABLE "user_activity_events" DROP COLUMN IF EXISTS "title";

-- Step 3: Remove the description column
ALTER TABLE "user_activity_events" DROP COLUMN IF EXISTS "description";
