/**
 * Comment Feed Listener
 *
 * Subscribes to Comment domain events and records feed activities in
 * the social module. Hosted in SocialModule — CommentModule does
 * not import SocialModule.
 *
 * The refactor removed the Q/A-era `comments_created` and
 * `comments_solved` activity types. The only remaining activity
 * generated by the comment module is `comment_created`, which is
 * reused for both top-level comments and replies — the social feed
 * renders them uniformly.
 *
 * Every other comment event is ignored.
 */

import { Inject, Injectable, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import { InjectPinoLogger, PinoLogger } from 'nestjs-pino';
import {
  COMMENT_DOMAIN_EVENT_BUS,
  type CommentDomainEventBusPort,
} from '@/modules/comment/domain/events';
import type {
  CommentCreatedEvent,
  CommentDomainEvent,
} from '@/modules/comment/domain/events/comment.events';
import { SocialService } from '../../domain/services/social.service';
import { getCorrelationId, createCorrelationId } from '@/common/interceptors/correlation-id';

@Injectable()
export class CommentFeedListenerAdapter implements OnModuleInit, OnModuleDestroy {
  private unsubscribe: (() => void) | null = null;

  constructor(
    @Inject(COMMENT_DOMAIN_EVENT_BUS)
    private readonly commentEventBus: CommentDomainEventBusPort,
    private readonly socialService: SocialService,
    @InjectPinoLogger(CommentFeedListenerAdapter.name)
    private readonly logger: PinoLogger,
  ) {}

  onModuleInit(): void {
    this.unsubscribe = this.commentEventBus.subscribe((event) => {
      void this.handleEvent(event);
    });
  }

  onModuleDestroy(): void {
    this.unsubscribe?.();
    this.unsubscribe = null;
  }

  private async handleEvent(event: CommentDomainEvent): Promise<void> {
    if (event.eventType !== 'comment_created') {
      return;
    }

    const correlationId = getCorrelationId() ?? createCorrelationId();

    await this.recordCommentCreated(event, correlationId);
  }

  private async recordCommentCreated(
    event: CommentCreatedEvent,
    correlationId: string,
  ): Promise<void> {
    this.logger.debug({
      event: 'social_feed_comment_created',
      correlationId,
      authorId: event.authorId,
      commentId: event.commentId,
      quizId: event.quizId,
      isReply: event.isReply,
    });

    await this.socialService.recordFeedActivity({
      userId: event.authorId,
      activityType: 'comment_created',
      occurredAt: event.timestamp.toISOString(),
      payload: {
        commentId: event.commentId,
        quizId: event.quizId,
        parentCommentId: event.parentCommentId,
        isReply: event.isReply,
      },
    });
  }
}
