import { randomUUID } from 'node:crypto';
import type { IncomingMessage, ServerResponse } from 'node:http'; // type of the request and response objects
import { ConfigService } from '@nestjs/config';
import type { Params } from 'nestjs-pino'; // type of the configuration object for nestjs-pino
import type { SerializedError, SerializedRequest, SerializedResponse } from 'pino-std-serializers'; // type of the serialized request, response, and error objects. For example, req will be serialized to only include the id, method, url, and headers. res will be serialized to only include the statusCode and headers. err will be serialized to only include the type, message, stack, and cause.

export const createPinoHttpConfig = (configService: ConfigService): Params => {
  const nodeEnv = configService.get<string>('NODE_ENV', 'development');
  const isProduction = nodeEnv === 'production';
  const isTest = nodeEnv === 'test';

  return {
    pinoHttp: {
      genReqId: (req, res) => {
        const existingId = req.headers['x-request-id'];
        const requestId =
          typeof existingId === 'string' && existingId.length > 0
            ? existingId
            : Array.isArray(existingId)
              ? String(existingId[0])
              : randomUUID();
        // if requestId is not a string, generate a new one

        res.setHeader('x-request-id', requestId);
        return requestId;
      },
      ...(isProduction
        ? {}
        : {
            transport: {
              target: 'pino-pretty',
              options: {
                colorize: true,
                singleLine: true,
                translateTime: 'SYS:standard',
              },
            },
          }),
      autoLogging: {
        ignore: (req) => {
          const url = req.url ?? '';
          return (
            url.startsWith('/health') || url.startsWith('/ready') || url.startsWith('/metrics')
          );
        },
      },

      // serializers are used to serialize the request, response, and error objects to a format that can be logged. For example, req will be serialized to only include the id, method, url, and headers. res will be serialized to only include the statusCode and headers. err will be serialized to only include the type, message, stack, and cause.
      // requestId is the id of the request, which is generated by the genReqId function.
      // correlationId is the id of the correlation, which is generated by the genCorrelationId function. Correlation id is used to track the request through the system. For example, if a user attempts to a quiz, there are multiple requests to the server, such as to get the quiz, to answer the quiz, to submit the quiz, etc. All these requests are related to the same quiz attempt, so they should have the same correlation id.
      serializers: {
        req: (req: SerializedRequest) => ({
          id: req.id,
          method: req.method,
          url: req.url,
          headers: {
            'x-request-id': req.headers['x-request-id'],
            'x-correlation-id': req.headers['x-correlation-id'],
            origin: req.headers.origin,
            'user-agent': req.headers['user-agent'],
          },
        }),
        res: (res: SerializedResponse) => ({
          statusCode: res.statusCode,
          headers: {
            'x-request-id': res.raw.getHeader('x-request-id'),
            'x-correlation-id': res.raw.getHeader('x-correlation-id'),
          },
        }),
        // err serializer is used to serialize the error object to a format that can be logged. For example, err will be serialized to only include the type, message, stack, and cause. Stack and cause are not included in production to avoid leaking sensitive information. Stack trace and cause are created by the error object itself and this object is created by throw new Error('...'), so we need to remove them in production to avoid leaking sensitive information.
        err: (err: SerializedError) => ({
          type: err.type,
          message: err.message,
          stack: isProduction ? undefined : err.raw.stack,
          cause: isProduction ? undefined : err.raw.cause,
        }),
      },
      customLogLevel: (_req: IncomingMessage, res: ServerResponse, err?: Error) => {
        // if the response status code is 500, return 'error' to log the error.
        if (err || res.statusCode >= 500) return 'error';
        // if the response status code is 400, return 'warn' to log the warning.
        if (res.statusCode >= 400) return 'warn';
        // if the response status code is 200, 201, 204, return 'info' to log the request and response.
        return 'info';
      },
      // customSuccessObject is used to log the request and response when the response status code is 200, 201, 204.
      customSuccessObject: (req: IncomingMessage, res: ServerResponse, responseTime: number) => ({
        event: 'http_request_completed',
        responseTime,
        method: req.method,
        url: req.url,
        statusCode: res.statusCode,
      }),
      customErrorObject: (
        req: IncomingMessage,
        res: ServerResponse,
        error: Error,
        responseTime: number,
      ) => ({
        event: 'http_request_failed',
        error: error.message,
        responseTime,
        method: req.method,
        url: req.url,
        statusCode: res.statusCode,
      }),
      level: isTest ? 'warn' : isProduction ? 'info' : 'debug',
    },
  };
};
