/**
 * RFC 7807 Problem Details for HTTP APIs
 *
 * @see https://tools.ietf.org/html/rfc7807
 */

export interface ProblemDetail {
  /**
   * A URI reference that identifies the problem type.
   * When dereferenced, it SHOULD return human-readable documentation.
   */
  readonly type: string;

  /** A short, human-readable summary of the problem type. */
  readonly title: string;

  /** The HTTP status code generated by the origin server. */
  readonly status: number;

  /** A human-readable explanation specific to this occurrence of the problem. */
  readonly detail?: string;

  /**
   * A URI reference that identifies the specific occurrence of the problem.
   * May be the absolute request URI.
   */
  readonly instance?: string;

  /**
   * Optional dictionary of additional members.
   * DTO validation errors are commonly included here.
   */
  readonly extensions?: Record<string, unknown>;
}

/**
 * Maps HTTP status codes to RFC 7807 type URIs.
 */
export const RFC7807_TYPE_URIS: Record<number, string> = {
  400: 'https://api.quiz.local/problems/bad-request',
  401: 'https://api.quiz.local/problems/unauthorized',
  403: 'https://api.quiz.local/problems/forbidden',
  404: 'https://api.quiz.local/problems/not-found',
  409: 'https://api.quiz.local/problems/conflict',
  422: 'https://api.quiz.local/problems/unprocessable-entity',
  423: 'https://api.quiz.local/problems/locked',
  429: 'https://api.quiz.local/problems/too-many-requests',
  500: 'https://api.quiz.local/problems/internal-server-error',
  /**
   * Reserved for the deprecated-route pattern (e.g. the singular
   * `/friend-request` stub in `SocialController`). The global exception
   * filter maps `HttpException` with status 405 through
   * `GLOBAL_METHOD_NOT_ALLOWED`, so callers receive a machine-readable
   * RFC 7807 envelope rather than a plain NestJS string.
   */
  405: 'https://api.quiz.local/problems/method-not-allowed',
};
