export const PROFILE_DISPLAY_NAME_MAX_LENGTH = 100;
export const PROFILE_BIO_MAX_LENGTH = 500;
export const PROFILE_AVATAR_URL_MAX_LENGTH = 2048;

export const USER_PAGINATION_DEFAULT_LIMIT = 20;

export const XP_PER_LEVEL = 500;
